[package]
name = "ultrafuzz-state"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha2 = { workspace = true }
thiserror = { workspace = true }
ultrafuzz-core = { path = "../ultrafuzz-core" }
ultrafuzz-topology = { path = "../ultrafuzz-topology" }

[dev-dependencies]
ultrafuzz-config = { path = "../ultrafuzz-config" }
tempfile = { workspace = true }

[lints]
workspace = true
