[package]
name = "ultrafuzz-prompts"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_yaml = { workspace = true }
thiserror = { workspace = true }
ultrafuzz-core = { path = "../ultrafuzz-core" }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true
