import { describe, expect, it } from "vitest";
import { eventCapabilitySatisfies, qualifyHarnessBinding, type HarnessCapabilities, type ProviderBinding } from "../src/index.js";
const provider: ProviderBinding = { id: "p", kind: "test", baseUrl: "https://example.test", auth: "api-key", credentialEnv: "TEST_KEY", protocols: ["openai-chat"], preflight: "first-request" };
const harness: HarnessCapabilities = { id: "h", executable: "node", version: "1", state: { mode: "run-scoped", configSeedDir: ".ultrafuzz/harness/h" }, protocols: ["openai-chat"], unattended: true, tools: { filesystem: true, shell: true }, events: "jsonl", sessions: "none", usage: { tokens: true, cache: false, cost: false }, reasoningLevels: ["high"], isolation: "external-sandbox-required" };
describe("provider harness qualification", () => {
  it("implements the event partial order", () => { expect(eventCapabilitySatisfies("jsonl", "final-text-only")).toBe(true); expect(eventCapabilitySatisfies("final-text-only", "jsonl")).toBe(false); expect(eventCapabilitySatisfies("rpc", "jsonl")).toBe(false); expect(eventCapabilitySatisfies("jsonl", "rpc")).toBe(false); });
  it("builds a credential-minimal child environment without retaining values in config", () => { const result = qualifyHarnessBinding({ profileId: "m", model: "opaque/catalogue-id", provider, harness, env: { PATH: process.env.PATH, TEST_KEY: "secret" } }); expect(result.diagnostics).toEqual([]); expect(result.binding?.childEnv).toEqual({ TEST_KEY: "secret" }); expect(JSON.stringify(result.binding?.provider)).not.toContain("secret"); });
  it("reports actionable profile fields before launch", () => { const result = qualifyHarnessBinding({ profileId: "m", model: "anything", reasoning: "max", provider, harness, requirements: { events: "rpc", cloudPortable: true }, env: { PATH: process.env.PATH } }); expect(result.binding).toBeUndefined(); expect(result.diagnostics.map((d) => d.path.join("."))).toEqual(expect.arrayContaining(["models.m.reasoning", "models.m.harness", "providers.p.api_key_env"])); });
  it("rejects credentials in argv", () => { const result = qualifyHarnessBinding({ profileId: "m", model: "x", provider, harness, env: { PATH: process.env.PATH, TEST_KEY: "secret" }, argv: ["--token", "secret"] }); expect(result.diagnostics.some((d) => d.code === "CONFIG_BINDING_ARGV_CREDENTIAL")).toBe(true); });
});
