export const MAX_NODE_ATTEMPT_FAILURE_MESSAGE_BYTES = 1_000;
export const MAX_NODE_ATTEMPT_FAILURE_MESSAGE_CODE_POINTS = 1_000;
export const MAX_GENERATED_TEST_BUNDLE_ENTRIES = 1_024;
export const MAX_GENERATED_TEST_BUNDLE_BYTES = 64 * 1024 * 1024;
export const MAX_GENERATED_TEST_COMPANION_BYTES = 16 * 1024 * 1024;
export const MAX_GENERATED_TEST_PATH_BYTES = 4_096;
export const MAX_GENERATED_TEST_PATH_SEGMENTS = 64;
