export const MAX_NODE_ATTEMPT_FAILURE_MESSAGE_BYTES = 1_000;
export const MAX_NODE_ATTEMPT_FAILURE_MESSAGE_CODE_POINTS = 1_000;
/** Maximum number of primary and fallback generations in one agent task. */
export const MAX_RETRY_CHAIN_ATTEMPTS = 100;
export const MAX_GENERATED_TEST_BUNDLE_ENTRIES = 1_024;
export const MAX_GENERATED_TEST_BUNDLE_BYTES = 64 * 1024 * 1024;
export const MAX_GENERATED_TEST_COMPANION_BYTES = 16 * 1024 * 1024;
export const MAX_GENERATED_TEST_PATH_BYTES = 4_096;
export const MAX_GENERATED_TEST_PATH_SEGMENTS = 64;
export const MAX_GENERATED_TEST_METADATA_CHARS = 16_384;
export const MAX_GENERATED_TEST_PROVENANCE_VALUE_CHARS = 4_096;
export const MAX_AGGREGATION_SOURCE_BUNDLES = 4_096;
export const MAX_AGGREGATION_SOURCE_ENTRIES = 65_536;
export const MAX_AGGREGATION_DECLARED_BYTES = 1024 * 1024 * 1024;
export const MAX_AGGREGATION_ABSOLUTE_PATH_CHARS = 16_384;
export const MAX_AGGREGATION_REASON_CHARS = 16_384;
