import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { assertNoSymlinkComponents, ensureSafeDirectory, writeFileDurable, type RunLayout } from "@ultrafuzz/artifacts";
import type { ResolvedConfig } from "@ultrafuzz/config";

// Agents learn both absolute paths from these variables rather than from the
// prompt. The prompt fragment therefore stays byte-identical across runs and
// nodes, so enabling the friction log never moves a prompt-cache boundary.
export const FRICTION_LOG_ENV = "ULTRAFUZZ_FRICTION_LOG";
export const FRICTION_LOG_DIR_ENV = "ULTRAFUZZ_FRICTION_LOG_DIR";
const FRICTION_LOG_ENVIRONMENT_VARIABLES = [FRICTION_LOG_ENV, FRICTION_LOG_DIR_ENV] as const;

const FRICTION_LOG_DIRECTORY = "friction";
const FRICTION_LOG_WRAPPER = "ultrafuzz-friction-log";
const FROG_INIT_TIMEOUT_MS = 60_000;
// Frog publishes with these. Removing them keeps every entry local to the run
// until an operator reviews it; target findings must never reach GitHub.
const PUBLISHING_ENVIRONMENT_VARIABLES = ["GITHUB_TOKEN", "GH_TOKEN", "GITHUB_API_URL"] as const;
// Frog anchors its log at `git rev-parse --show-toplevel`, and run roots sit
// inside the target repository. Without these, Frog would write into the
// target's root and read the target's remote and commit into entries.
const GIT_DISCOVERY_ENVIRONMENT_VARIABLES = ["GIT_DIR", "GIT_WORK_TREE"] as const;

export interface FrictionLogEnvironment {
  env: Record<string, string | undefined>;
  environmentVariableNames: readonly string[];
  active: boolean;
}

/**
 * Prepares the run-owned Frog friction log when `run.friction_log_enabled` is
 * set. The log lives at `<run root>/friction`, outside every target worktree and
 * outside per-attempt artifact directories, which retries wipe. Agents write to
 * it only through a generated wrapper around the pinned Frog CLI that allows
 * `log` and `list`, fixes the log directory, and strips publishing credentials.
 */
export function prepareFrictionLogEnvironment(input: {
  layout: RunLayout;
  config: ResolvedConfig;
  env?: Record<string, string | undefined>;
}): FrictionLogEnvironment {
  const env = { ...(input.env ?? {}) };
  if (input.config.run.frictionLogEnabled !== true) {
    return { env, environmentVariableNames: [], active: false };
  }

  const frogBin = resolveFrogBin();
  const logRoot = ensureSafeDirectory(input.layout.root, FRICTION_LOG_DIRECTORY);
  if (!fs.existsSync(path.join(logRoot, ".agents", "friction-log", "config.json"))) {
    initializeFrictionLog(frogBin, logRoot);
  }

  const wrapperPath = path.join(logRoot, FRICTION_LOG_WRAPPER);
  assertNoSymlinkComponents(input.layout.root, wrapperPath, "friction log wrapper");
  writeFileDurable(wrapperPath, frictionLogWrapper(process.execPath, frogBin, logRoot));
  fs.chmodSync(wrapperPath, 0o700);

  return {
    env: { ...env, [FRICTION_LOG_ENV]: wrapperPath, [FRICTION_LOG_DIR_ENV]: logRoot },
    environmentVariableNames: FRICTION_LOG_ENVIRONMENT_VARIABLES,
    active: true
  };
}

export function resolveFrogBin(): string {
  const entrypoint = fileURLToPath(import.meta.resolve("frog"));
  const bin = path.join(path.dirname(entrypoint), "bin.js");
  if (!fs.statSync(bin, { throwIfNoEntry: false })?.isFile()) {
    throw new Error(`pinned Frog CLI is missing its executable: ${bin}`);
  }
  return bin;
}

function initializeFrictionLog(frogBin: string, logRoot: string): void {
  const result = spawnSync(process.execPath, [frogBin, "init", "--no-inbound", "--cwd", logRoot, "--format", "json"], {
    encoding: "utf8",
    env: frogEnvironment(process.env, logRoot),
    timeout: FROG_INIT_TIMEOUT_MS
  });
  if (result.error !== undefined || result.status !== 0) {
    const detail = result.error?.message ?? (result.stderr || result.stdout).trim();
    throw new Error(`failed to initialize the run friction log: ${detail}`);
  }
}

function frogEnvironment(source: NodeJS.ProcessEnv, logRoot: string): NodeJS.ProcessEnv {
  const removed = new Set<string>([...PUBLISHING_ENVIRONMENT_VARIABLES, ...GIT_DISCOVERY_ENVIRONMENT_VARIABLES]);
  return {
    ...Object.fromEntries(Object.entries(source).filter(([name]) => !removed.has(name))),
    GIT_CEILING_DIRECTORIES: path.dirname(logRoot)
  };
}

export function frictionLogWrapper(nodePath: string, frogBin: string, logRoot: string): string {
  return `#!/bin/sh
# Generated by Ultrafuzz. Records agent friction in this run with the pinned
# Frog CLI. Publishing is an operator step after review, never an agent step.
set -eu
case "\${1-}" in
  log | list) ;;
  *)
    echo "ultrafuzz friction log: only 'log' and 'list' are available" >&2
    exit 2
    ;;
esac
for argument in "$@"; do
  case "$argument" in
    --publish | --publish=* | --target | --target=* | -t* | --token | --token=* | --cwd | --cwd=* | --open)
      echo "ultrafuzz friction log: $argument is not available inside a run" >&2
      exit 2
      ;;
  esac
done
unset ${[...PUBLISHING_ENVIRONMENT_VARIABLES, ...GIT_DISCOVERY_ENVIRONMENT_VARIABLES].join(" ")}
GIT_CEILING_DIRECTORIES=${shellQuote(path.dirname(logRoot))}
export GIT_CEILING_DIRECTORIES
exec ${shellQuote(nodePath)} ${shellQuote(frogBin)} "$@" --cwd ${shellQuote(logRoot)}
`;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}
