import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

// Run-relative locations. Frog writes entries to
// `<run>/friction/.agents/friction-log/<id>/friction.md` once Git discovery is
// fenced off; that is the one run directory agents are told to write. The
// wrapper sits beside it, and preparation rewrites it before every task.
// Neither placement stops an agent: agents run unsandboxed (docs/security.md).
export const FRICTION_LOG_ENTRIES_PATH = "friction";
export const FRICTION_LOG_COMMAND_PATH = "friction-bin/ultrafuzz-friction-log";
// Frog anchors its log at `git rev-parse --show-toplevel`, and run roots sit
// inside the target repository, so unfenced discovery makes Frog write into the
// target's root and validate entries against the target's issue forms. With
// GIT_DIR set, Git does no discovery, and it fails when GIT_DIR names nothing,
// so Frog uses `--cwd` as its root. GIT_CEILING_DIRECTORIES is no fence: it is a
// `:`-separated list, so a run root containing `:` is split and is no ceiling.
const FRICTION_LOG_NO_GIT_DIR_PATH = `${path.posix.dirname(FRICTION_LOG_COMMAND_PATH)}/no-git`;
// Frog's last GitHub credential source is `gh auth token`. A GH_CONFIG_DIR that
// names nothing hides a token gh keeps in its config file, but gh also reads
// the system keyring, so neither this nor unsetting the variables below removes
// a credential. Frog keeps entries local because no command the wrapper accepts
// publishes or reads from GitHub.
const FRICTION_LOG_NO_GH_CONFIG_PATH = `${path.posix.dirname(FRICTION_LOG_COMMAND_PATH)}/no-gh`;

// Frog publishes with these.
const PUBLISHING_ENVIRONMENT_VARIABLES = ["GITHUB_TOKEN", "GH_TOKEN", "GITHUB_API_URL"] as const;
// FROG_DATABASE_URL makes `log` and `list` use that Postgres database instead of
// the run's files.
const STORE_ENVIRONMENT_VARIABLES = ["FROG_DATABASE_URL", "FROG_NAMESPACE", "FROG_SCHEMA"] as const;
// incur, the CLI framework Frog is built on, acts on these wherever they appear
// in argv (extractBuiltinFlags, incur 0.4.25), even where an option value
// belongs: `log x --body --mcp` would start Frog's MCP server, which serves
// `publish`. So none of them is accepted as an option value either.
const INCUR_BUILTIN_FLAGS = [
  "--full-output",
  "--llms",
  "--llms-full",
  "--mcp",
  "--help",
  "-h",
  "--update",
  "--incur-update-check",
  "--version",
  "--schema",
  "--json",
  "--format",
  "--filter-output",
  "--token-limit",
  "--token-offset",
  "--token-count"
] as const;

/** The pinned Frog CLI's executable, resolved from Ultrafuzz's own install. */
export function resolveFrogBin(): string {
  const entrypoint = fileURLToPath(import.meta.resolve("frog"));
  const bin = path.join(path.dirname(entrypoint), "bin.js");
  if (!fs.statSync(bin, { throwIfNoEntry: false })?.isFile()) {
    throw new Error(`pinned Frog CLI is missing its executable: ${bin}`);
  }
  return bin;
}

/**
 * The agent-facing friction log command. It runs the pinned Frog CLI and
 * accepts only `log` and `list` with their local options, so it cannot be used
 * to publish, update Frog, start its MCP server, or point Frog elsewhere. That
 * guards against misuse by mistake and enforces nothing: an agent can run Frog,
 * or anything else, directly. It pins `--cwd` ahead of every agent argument, so
 * no argument can consume or replace it, and it finds the run from its own
 * location, so its bytes are identical for every run.
 *
 * Frog reads /dev/null as stdin: with a terminal on stdin and stderr, `log`
 * prompts for a missing title or severity and, without --body, opens $EDITOR
 * on the entry. incur's update check, which runs when stdout is a terminal,
 * fetches Frog's latest version from the npm registry in a detached process;
 * NO_UPDATE_NOTIFIER turns it off.
 */
export function frictionLogWrapper(nodePath: string, frogBin: string): string {
  return `#!/bin/sh
# Generated by Ultrafuzz. Records agent friction in this run with the pinned
# Frog CLI. Publishing is an operator step after review, never an agent step.
set -eu
refuse() {
  echo "ultrafuzz friction log: $1" >&2
  exit 2
}
case "\${1-}" in
  log | list) command=$1 ;;
  *) refuse "only 'log' and 'list' are available" ;;
esac
shift
value=
for argument in "$@"; do
  if [ -n "$value" ]; then
    value=
    case "$argument" in
      ${INCUR_BUILTIN_FLAGS.join(" | ")}) refuse "$argument is not available inside a run" ;;
    esac
    continue
  fi
  case "$command $argument" in
    "log --body" | "log -b" | "log --severity" | "log -s" | "log --label" | "log --format" | "list --format")
      value=1
      continue
      ;;
    "log --body="* | "log --severity="* | "log --label="* | "log --force")
      continue
      ;;
  esac
  case "$argument" in
    -*) refuse "$argument is not available inside a run" ;;
  esac
done
[ -z "$value" ] || refuse "the last option is missing its value"
run_root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd -P)
unset ${[...PUBLISHING_ENVIRONMENT_VARIABLES, ...STORE_ENVIRONMENT_VARIABLES, "GIT_WORK_TREE"].join(" ")}
GIT_DIR=$run_root/${FRICTION_LOG_NO_GIT_DIR_PATH}
GH_CONFIG_DIR=$run_root/${FRICTION_LOG_NO_GH_CONFIG_PATH}
NO_UPDATE_NOTIFIER=1
export GIT_DIR GH_CONFIG_DIR NO_UPDATE_NOTIFIER
exec ${shellQuote(nodePath)} ${shellQuote(frogBin)} "$command" --cwd "$run_root/${FRICTION_LOG_ENTRIES_PATH}" "$@" </dev/null
`;
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'\\''`)}'`;
}
